"""empty message

Revision ID: 6ea9c1edffee
Revises: 3e7597ad3ddf
Create Date: 2020-08-07 03:02:04.643054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea9c1edffee'
down_revision = '3e7597ad3ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('artists', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('venues', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('venues', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'updated_at')
    op.drop_column('venues', 'created_at')
    op.drop_column('artists', 'updated_at')
    op.drop_column('artists', 'created_at')
    # ### end Alembic commands ###
